/**																
	\file File_Data_Struct.h
  	\brief File_Data_Struct.h contains declaration of the structures used for collecting the Online digital data 
	\details This structure is used to save the extracted information from the file generated by digital pad.
  	\date 27/06/2007 (Date of Creation)
	\date 09/04/2010 (Last modified)
  	\author Jeganathan Krishnasamy,Manish Kumar Gupta
  	\version 1.1.0.0
  	<b> All COPYRIGHTS ARE RESERVERD TO C-DAC GIST PUNE 2012 </b>
*/

#ifndef _FILE_DATA_STRUCT_H_
#define _FILE_DATA_STRUCT_H_

#ifdef __cplusplus

extern "C"
{  
	
#endif
	/**FILE_POINTINFO
	\brief  Data strucute used to store Point information Sent to Recognition Engine DLL
	*/
	typedef struct 
	{
		//unsigned short x; /**< X Value */
		//unsigned short y;/**< Y Value */
		double x;
		double y;
		unsigned short p;/**< Pressure */
	}FILE_POINTINFO;

	/** FILE_STROKEINFO
    \brief  Data strucute used to store Stroke information  Sent to Recognition Engine DLL
	*/
	typedef struct 
	{
		char strColor;/**<Storing Color of the stroke */
		unsigned short nStrokeType;/**< not used*/
		int nstroke; //No. of strokes
		unsigned short nPointCount;/**< No of points in stroke*/
		FILE_POINTINFO* ptrPointInfo;/**< pointer to array of points*/
	}FILE_STROKEINFO;

#ifdef __cplusplus
}  
#endif

#endif



